### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by GrimbiXcode** [alpenwasser/fhnwfactsheet#14]
A gitignore-template would be very handy for use with git.

My suggestion:

```
# latex compiler aux-files 
# ========================== 
*.aux 
*.bbl 
*.fdb_latexmk 
*.fls 
*.out 
*.txt 
*.synctex.gz 
*.toc 
*.log 
*.blg 
*.pdf 
*.ilg 
*.glo 
!img/*.pdf 
```

**Comment by alpenwasser** [comment]
Oh wow, must've overlooked this in my notifications! Terribly sorry!

And yes, good idea -- will do, thanks!
